import type { LucideIcon } from "lucide-react";
import {
    Home,
    Search,
    Settings,
    User,
    Calendar,
    ShoppingCart,
    FileText,
    ChevronDown,
    FilePlus2,
    FileSearch,
    FileClock,
    Package,
    DollarSign,
    ChartLine,
    RefreshCcw,
    Eye,
    Edit,
    ArrowUp,
    ArrowDown,
    ListFilter,
    SquareArrowOutUpRight,
    ChevronLeft,
    ChevronRight,
    CircleUserRound,
    UserRoundPlus,
    UserRoundPen,
    FileType,
} from "lucide-react";

// Pick ONLY the icons your app should use.
// Add/remove here to control what's allowed.
export const ICONS = {
    home: Home,
    search: Search,
    settings: Settings,
    customer: CircleUserRound,
    staff: User,
    calendar: Calendar,
    order: ShoppingCart,
    invoice: FileText,
    chevronDown: ChevronDown,
    newInvoice: FilePlus2,
    searchInvoice: FileSearch,
    invoiceHistory: FileClock,
    product: Package,
    price: DollarSign,
    chart: ChartLine,
    reset: RefreshCcw,
    view: Eye,
    edit: Edit,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    filter: ListFilter,
    squareArrow: SquareArrowOutUpRight,
    arrowLeft: ChevronLeft,
    arrowRight: ChevronRight,
    staffAdd: UserRoundPlus,
    staffEdit: UserRoundPen,
    productTypeNew: FileType,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
