services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./app
          action: sync
        - path: ./package.json
          action: rebuild
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    depends_on:
      - db

volumes:
  postgres_data:
    name: ch2k-office-db
